package ru.andrei.advertisingstand.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TopGoodsWs", targetNamespace = "http://impl.services.web.tsystemsverificationwork.andrei.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TopGoodsWs {


    /**
     * 
     * @return
     *     returns java.util.List<ru.andrei.tsystemsverificationwork.web.services.impl.StatisticsGoods>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTopTenGoods", targetNamespace = "http://impl.services.web.tsystemsverificationwork.andrei.ru/", className = "ru.andrei.tsystemsverificationwork.web.services.impl.GetTopTenGoods")
    @ResponseWrapper(localName = "getTopTenGoodsResponse", targetNamespace = "http://impl.services.web.tsystemsverificationwork.andrei.ru/", className = "ru.andrei.tsystemsverificationwork.web.services.impl.GetTopTenGoodsResponse")
    @Action(input = "http://impl.services.web.tsystemsverificationwork.andrei.ru/TopGoodsWs/getTopTenGoodsRequest", output = "http://impl.services.web.tsystemsverificationwork.andrei.ru/TopGoodsWs/getTopTenGoodsResponse")
    public List<StatisticsGoods> getTopTenGoods();

}
