package ru.andrei.advertisingstand.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TopGoodsWsService", targetNamespace = "http://impl.services.web.tsystemsverificationwork.andrei.ru/", wsdlLocation = "http://localhost:8080/store/topgoods?wsdl")
public class TopGoodsWsService
    extends Service
{

    private final static URL TOPGOODSWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOPGOODSWSSERVICE_EXCEPTION;
    private final static QName TOPGOODSWSSERVICE_QNAME = new QName("http://impl.services.web.tsystemsverificationwork.andrei.ru/", "TopGoodsWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/store/topgoods?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOPGOODSWSSERVICE_WSDL_LOCATION = url;
        TOPGOODSWSSERVICE_EXCEPTION = e;
    }

    public TopGoodsWsService() {
        super(__getWsdlLocation(), TOPGOODSWSSERVICE_QNAME);
    }

    public TopGoodsWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOPGOODSWSSERVICE_QNAME, features);
    }

    public TopGoodsWsService(URL wsdlLocation) {
        super(wsdlLocation, TOPGOODSWSSERVICE_QNAME);
    }

    public TopGoodsWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOPGOODSWSSERVICE_QNAME, features);
    }

    public TopGoodsWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TopGoodsWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TopGoodsWs
     */
    @WebEndpoint(name = "TopGoodsWsPort")
    public TopGoodsWs getTopGoodsWsPort() {
        return super.getPort(new QName("http://impl.services.web.tsystemsverificationwork.andrei.ru/", "TopGoodsWsPort"), TopGoodsWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TopGoodsWs
     */
    @WebEndpoint(name = "TopGoodsWsPort")
    public TopGoodsWs getTopGoodsWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.services.web.tsystemsverificationwork.andrei.ru/", "TopGoodsWsPort"), TopGoodsWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOPGOODSWSSERVICE_EXCEPTION!= null) {
            throw TOPGOODSWSSERVICE_EXCEPTION;
        }
        return TOPGOODSWSSERVICE_WSDL_LOCATION;
    }

}
